{{- if .Values.create_infra }}
{{- if .Values.google.config_connector_context }}

apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnectorContext
metadata:
  name: configconnectorcontext.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: {{ include "app_admin_sa" $ }}

{{- end }}
{{- end }}
