{{- if .Values.create_infra }}
{{- if .Values.google.create_registry }}

apiVersion: artifactregistry.cnrm.cloud.google.com/v1beta1
kind: ArtifactRegistryRepository
metadata:
  name: {{ include "registry_name" . }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ include "app_project_id" . }}
spec:
  format: DOCKER
  location: {{ required "REQUIRED: google.region" .Values.google.region }}

{{- end }}
{{- end }}
